### ISSUE TITLE
new project creation broken

### ISSUE THREAD

**Issue by rvanderwerf** [mariogarcia/grooid-templates#3]
When I make a new project I get a build failure on AS 1.2.2 I get a build failure with the emerger plugin. I couldn't seem to find the home or locate it on plugins.gradle.org so I couldn't look further into it.

classpath 'net.kaleidos.gradle.plugins:emerger:0.0.1'
apply plugin: 'net.kaleidos.gradle.plugins.emerger'

during initial gradle sync I get the following error:
Error:(14, 0) Cause: net/kaleidos/gradle/plugins/emerger/EmergerPlugin : Unsupported major.minor version 52.0

settings used during lazybones template creation:
package domain: com.example.rvanderwerf
min sdk: 15
max: 21
all other settings defaults

**Comment by mariogarcia** [comment]
Oh my! It seems like I compiled the `emerger` plugin with JDK8. I'm so sorry I would be releasing a new version in the morning. 

In the meantime, as a workaround, you can clone the plugin source code (https://github.com/kaleidos/emerger) and install it locally (with jdk7 of course). And then in your Android app just add the maven local repo:

```groovy
repositories {
   mavenLocal()
}
```

Bottom line, it's a bug but not from `grooid-templates` but from `emerger` plugin.

**Comment by mariogarcia** [comment]
I've published a new `emerger` plugin version properly compiled at jcenter.  Could you please try again changing `emerger` version from 0.0.1 to 0.0.2.
